#version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: customers
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  streamlit:
    build: ./app
    container_name: streamlit_app
    restart: always
    depends_on:
      - db
    command: sh -c "until nc -z db 3306; do echo 'Waiting MySQL...'; sleep 2; done; streamlit run main.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app

volumes:
  db_data:
