[supabase]
SUPABASE_URL= "https://wjyagqbymdpcfdmqlzue.supabase.co"
SUPABASE_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqeWFncWJ5bWRwY2ZkbXFsenVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTQ0NzAsImV4cCI6MjA3MzgzMDQ3MH0.fv4cZ9K7Xe4zMOUeU9X35mQaOlaRefwD_YkCJcKAWJQ"

[client]
COOKIES_PASSWORD="qeWFncWJ5bWRwY2Z"